{"name": "test_calc_sum[5-7-11]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 11", "trace": "input1 = 5, input2 = 7, output = 11\n\n    @pytest.mark.parametrize(\"input1, input2, output\", [\n        (2,3,5),\n        (4,4,8),\n        (5,7,11)\n    ])\n    \n    def test_calc_sum(input1,input2, output):\n        result = sum(input1,input2)\n>       assert result == output\nE       assert 12 == 11\n\ntest_parametarization_demo.py:13: AssertionError"}, "parameters": [{"name": "input1", "value": "5"}, {"name": "input2", "value": "7"}, {"name": "output", "value": "11"}], "start": 1586570642058, "stop": 1586570642059, "uuid": "67b29cb1-755e-4ded-bb32-159a6a0f2c1c", "historyId": "3f941f7d44ec5bc5377dbfcd656505d3", "testCaseId": "99129c356f1bd9823f190dce9f743791", "fullName": "test_parametarization_demo#test_calc_sum", "labels": [{"name": "suite", "value": "test_parametarization_demo"}, {"name": "host", "value": "LAPTOP-QCGVCH7O"}, {"name": "thread", "value": "7860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parametarization_demo"}]}